# Generated by Django 3.2.12 on 2023-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231025_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('not_done', 'Не исполнено'), ('in_progress', 'Взят в работу'), ('done', 'Исполнено')], default='not_done', max_length=250, verbose_name='статус заказа'),
        ),
    ]
