# Generated by Django 3.2.12 on 2023-10-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0005_auto_20231025_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cart.CartItem'),
        ),
    ]
