# Generated by Django 3.2.12 on 2023-10-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
