# Generated by Django 3.2.23 on 2023-12-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0007_auto_20231219_1246'),
        ('orders', '0008_auto_20231030_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='kompany.product', verbose_name='название товара'),
        ),
    ]
