# Generated by Django 3.2.12 on 2023-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormObratZvonot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='имя')),
                ('body', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'обратный звонок',
                'verbose_name_plural': 'обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ikons', models.CharField(max_length=500, verbose_name='иконка соцсети')),
                ('network_image', models.ImageField(blank=True, upload_to='network_image', verbose_name='картинка соцсети')),
                ('url_network', models.TextField(blank=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'социальные сети',
                'verbose_name_plural': 'социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=500, verbose_name='вопрос')),
                ('body_question', models.TextField(blank=True, default='', verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'вопросы',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Onas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_onas1', models.CharField(max_length=500, verbose_name='заголовок')),
                ('title_onas2', models.CharField(blank=True, max_length=500, verbose_name='второй заголовок')),
                ('body_onas', models.TextField(blank=True, default='', verbose_name='текст')),
                ('image_uslugi', models.ImageField(blank=True, upload_to='home', verbose_name='главное фото')),
                ('question', models.ManyToManyField(to='kompany.Question', verbose_name='вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_contact', models.CharField(max_length=200, verbose_name='контакт')),
                ('body_contact', models.TextField(blank=True, default='', verbose_name='текст контакта')),
                ('adress_one_contact', models.TextField(blank=True, default='', verbose_name='адрес')),
                ('tel', models.CharField(max_length=200, verbose_name='телефон')),
                ('web', models.TextField(blank=True, default='', verbose_name='email')),
                ('network_ikons', models.ManyToManyField(blank=True, default='', to='kompany.Network', verbose_name='иконки соцсетей')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакт',
            },
        ),
    ]
