# Generated by Django 3.2.12 on 2023-10-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0002_auto_20231009_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопросы', 'verbose_name_plural': 'вопросы на странице о нас'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='Pod_Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='брент')),
                ('image', models.ImageField(blank=True, upload_to='подбрент', verbose_name='подбренд')),
                ('product', models.ManyToManyField(to='kompany.Product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Под бренд',
                'verbose_name_plural': 'Под бренд',
            },
        ),
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='брент')),
                ('pod_brend', models.ManyToManyField(to='kompany.Pod_Brend', verbose_name='под бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='product',
            field=models.ManyToManyField(related_name='homes', to='kompany.Product', verbose_name='товар'),
        ),
    ]
