# Generated by Django 3.2.12 on 2023-10-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0005_auto_20231013_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='srok',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cрок поставки'),
        ),
    ]
