# Generated by Django 3.2.12 on 2023-12-20 14:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompany', '0008_product_pop_prodaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='описание'),
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompany.brend')),
                ('pod_brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompany.pod_brend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompany.product')),
            ],
            options={
                'verbose_name': 'Связь продукта, бренда и подбренда',
                'verbose_name_plural': 'Связи продуктов, брендов и подбрендов',
            },
        ),
    ]
